场景A: 
  - "promt_1"
  - "promt_2"
  - "promt_3"
  - "promt_4"
  - "promt_5"
  - "promt_6"
  - "promt_7"
  - "promt_8"
  - "promt_9"
  - "promt_10"
场景B: 
  - "promt_1"
  - "promt_2"
  - "promt_3"
  - "promt_4"
  - "promt_5"
  - "promt_6"
  - "promt_7"
  - "promt_8"
  - "promt_9"
  - "promt_10"
场景C: 
  - "promt_1"
  - "promt_2"
  - "promt_3"
  - "promt_4"
  - "promt_5"
  - "promt_6"
  - "promt_7"
  - "promt_8"
  - "promt_9"
  - "promt_10"
场景D: 
  - "promt_1"
  - "promt_2"
  - "promt_3"
  - "promt_4"
  - "promt_5"
  - "promt_6"
  - "promt_7"
  - "promt_8"
  - "promt_9"
  - "promt_10"
场景E: 
  - "promt_1"
  - "promt_2"
  - "promt_3"
  - "promt_4"
  - "promt_5"
  - "promt_6"
  - "promt_7"
  - "promt_8"
  - "promt_9"
  - "promt_10"
