场景A: 
  role_system_content: "你是一名专业的医生"
  role_user_content:
    - "promt_1"
    - "promt_2"
    - "promt_3"
    - "promt_4"
    - "promt_5"
    - "promt_6"
    - "promt_7"
    - "promt_8"
    - "promt_9"
    - "promt_10"
场景B: 
  role_system_content: "你是一名专业的医生"
  role_user_content:
    - "promt_1"
    - "promt_2"
    - "promt_3"
    - "promt_4"
    - "promt_5"
    - "promt_6"
    - "promt_7"
    - "promt_8"
    - "promt_9"
    - "promt_10"
场景C: 
  role_system_content: "你是一名专业的医生"
  role_user_content:
    - "promt_1"
    - "promt_2"
    - "promt_3"
    - "promt_4"
    - "promt_5"
    - "promt_6"
    - "promt_7"
    - "promt_8"
    - "promt_9"
    - "promt_10"
场景D: 
  role_system_content: "你是一名专业的医生"
  role_user_content:
    - "promt_1"
    - "promt_2"
    - "promt_3"
    - "promt_4"
    - "promt_5"
    - "promt_6"
    - "promt_7"
    - "promt_8"
    - "promt_9"
    - "promt_10"
场景E: 
  role_system_content: "你是一名专业的医生"
  role_user_content:
    - "promt_1"
    - "promt_2"
    - "promt_3"
    - "promt_4"
    - "promt_5"
    - "promt_6"
    - "promt_7"
    - "promt_8"
    - "promt_9"
    - "promt_10"
